### ISSUE TITLE
Request for PIC firmware

### ISSUE THREAD

**Issue by jschornick** [Exadler/DMCC_Library#4]
Given the open nature of the DMCC project, I was surprised that I haven't been able to locate the firmware that runs on the DMCC's own PIC microcontroller.  

In addition to tossing a blanket "open is better" statement your way, I would find it highly beneficial to have access to the firmware source for the purpose of debugging.  While I've enjoyed working with your design thus far, I have faced a few frustrations which could have been minimized if I simply knew what was going on inside the PIC.  

Some specific examples...
* Debugging the I2C protocol would be more straightforward if I could confirm that the problem was on the host or device side.  Right now, the latter is a black box, and certain features might simply not be implemented.
* PID tuning would be easier if I had a better feel for how you're interpreting the PID constants.  The behavior of the integration term appears to be using a decay, but that's purely conjecture without seeing the actual algorithmic implementation.

I can't think of any negatives to opening up your firmware, and perhaps I've simply missed where you've posted it online.  Can you clarify Exadler's stance on this issue?  Thanks!

**Comment by davidj55** [comment]
Open sourcing would help us too. We would like to see a deadman switch implemented. The DMCC can keep driving even if the BBB crashes. 

Also on our wish list is user set DMCC run over-current protection. The DMCC can handle this much faster than the BBB. The BBB doesn't deal with brownouts well, which can because by motor overcurrent.

A DMCC implemented time delay on change of direction would also help minimize brownwouts.

Lastly, has anyone seen the position data jump to +65K when it counts down to zero and then should go negative?

**Comment by paulctan** [comment]
Firmware is now released - [https://github.com/Exadler/DMCC_Firmware](https://github.com/Exadler/DMCC_Firmware)

**Comment by paulctan** [comment]
David:  Deadman switches/watchdog will add additional complexity to the normal use of the DMCC (Imagine someone using a DMCC that didn't hit the watchdog timer, and the DMCC shuts down).  For simple use, I don't think a watchdog at the DMCC level is viable.  It does exactly what you told it to do.  The Beaglebone brownouts should be fixed in hardware, not software.  Just build a better power supply circuit that isolates the motor power from the Beaglebone power.  I think you are trying to fix a hardware problem by patching software, and I think that is actually a bad idea.  You should fix the root of the problem - the power supply dropouts - just isolate the motor PSU from the Beaglebone PSU.

**Comment by davidj55** [comment]
Paul, I wouldn't agree with that philosophy. Firstly, he problem is not simply a power supply problem, that is just how it manifest it self quickly with what we are working on. With all of our PIC based products we run watchdog timers, it is just good industrial design. A product should fail safely. There is also the problem of other software glitches that are not power supply related causing problems also. Essentially the system does not fail safely if the DMCC continues to drive when the rest of the BBB system fails. Actually, good industrial design does shut down products if they are not properly controlled. It is easy to see a scenario where the BBB goes into some state that locks it up, or the BBB fails completely. The DMCC would then drive  a motor forever (or until something else fails) doing who knows what possible damage.

We only have one power supply - these things are located on vehicles and other locations where 2 power supplies are not feasible.  Adding two power supplies doesn't seem like a good product design if it could be better fixed in software, which is where this problem really lies. For starters it adds additional costs to a product which could be avoided by a software change. To me that seems like an obvious choice.

There is a deadman switch in the BBB (Linux) but when you do a BBB reset the DMCC doesn't reset and keeps driving. Which means is that the DMCC will continue driving until the BBB reboots fully, which might be 10-20 seconds.

We have already decided we need a better deadman system for the BBB since we cannot guarantee it will properly recover from an error.

**Comment by davidj55** [comment]
Paul:  What compiler are you using?  What/where are the programming pins for the DMCC?

**Comment by paulctan** [comment]
David,

You are welcome to your own opinion, but I'm just giving you my professional advice as a Professional Engineer.  I have built mission critical and life critical military hardware and software, so I'm not just saying what I'm saying without any experience to back it up.

Having said that, there are ways of engineering a single cost effective power supply that would isolate two rails.  It is not that big a deal to design.  If you are unsure of how to do this, perhaps you should ask some FAEs to come in and help you with your design.   As an example of where to start, look at Linear Technologies power products (they are not the cheapest, but you can use them as a place to start) -- http://www.linear.com/products/powerpath_controllers_*_ideal_diodes

The reason your comments are raising red flags in my mind, is that having a BeagleBone continually reset because of brownout conditions is a recipe for disaster.  Linux is not meant or designed to recover nicely from constant reboots!  If you are still using the stock Linux in a situation where you are getting brownouts and reboots, you are designing a system that will ultimately fail in time.

Putting a deadman switch will only put a band aid on a gaping mortal wound that is bound to bleed out.

Just my $0.02 worth (actually, my normal consulting rates are much, much higher ;).

**Comment by davidj55** [comment]
Paul,  I am not sure where you get the idea that brown outs conditions will be frequent. We are doing early testing and testing as many bad things as possible, so we are generating errors deliberately right now. We need to see what can fail and design around it. We would not design a product that needed to reboot often but there must be a recovery route from as many error conditions as possible. In the event of an error condition we must fail safe. You are focusing on the power supply issue, but that just highlighted to us that the DMCC doesn't shut down in the worst case scenarios (such as any failure of the BBB). The fact that a failure of the BBB can leave the DMCC driving uncontrolled is not a power supply issue.

Is the source code you posted complete?
